### ISSUE TITLE
Parsing with different formats instead only with default

### ISSUE THREAD

**Issue by caironoleto** [carlosantoniodasilva/i18n_alchemy#12]
Hi mate! 

In our project, we have the following config locale:

``` yml
pt:
  date:
    default: "%d/%m/%Y"
    competence: "%m/%Y"
```

Sometimes we need handle a date field in `competence` format, but we don't want to change our default format, we want to use `competence` format.

How we can do that?
